In [12]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import os
from sklearn.metrics import classification_report, confusion_matrix


wifi_data = pd.read_csv("wifi_data_2.csv")
#Old-------------------------------------------
# unknowndata = pd.read_csv("unknown_data.csv")
#New-------------------------------------------
unknowndata = pd.read_csv("wifi_data_1.csv")
filename="predictionFile"
#print("Dimensions of the data:")
#print(wifi_data.shape)
#print("\nFirst few records:")
#print(wifi_data.head())

X = wifi_data.drop('id', axis=1)  #contains attributes
y = wifi_data['id']

ssid_train, ssid_test, id_train, id_test = train_test_split(X, y, test_size = 0.6)
print(len(ssid_test),len(id_test))

svclassifier = SVC(kernel='linear')
svclassifier.fit(ssid_train, id_train)
prediction=np.array([-100.0,-61.0,-100.0,-100.0,-62.0,-100.0,-79.0,-66.0,-100.0])
prediction=prediction.reshape(1,-1)
id_pred = svclassifier.predict(ssid_test)
# New-------------------------------------------
unknowndata = unknowndata.drop('id', axis=1)
l = svclassifier.predict(unknowndata)

print(l)
def write_to_csv():
    global unknowndata
    global filename,l
    count = 0
    unknowndata=unknowndata.values
    print(unknowndata)
    result = {"f0:ec:af:cf:6c:e1":-200,"c9:a6:4d:9b:c0:8c":-200,"c2:b6:6e:70:fa:f7":-200,"d9:5f:f5:4f:10:89":-200,
             "c4:52:32:5c:31:e7":-200,"e9:3c:4a:34:13:fb":-200,"ed:61:e4:e8:22:30":-200,"ea:01:26:75:a4:c3":-200,
              "d0:4e:10:2e:cb:84":-200,"e4:e0:0a:ae:fd:e2":-200,"fa:35:76:56:6f:e3":-200,"d5:b7:dc:69:ca:ae":-200,
             "ca:81:7a:d7:55:49":-200,"e7:2b:ea:2f:95:c5":-200,"d4:32:fc:b5:f0:b5":-200}
    z=list(result.keys())
    for i in range(len(unknowndata)):
        print(unknowndata[i])
        for r in range (len(z)):
            result[z[r]]=unknowndata[i][r]
        result["id"]=l[i]
        df = pd.Series(result).to_frame().T
        df.to_csv(filename, index=False, mode='a', header=(not os.path.exists(filename)))
        count = 0
print(id_pred)
write_to_csv()

3462 3462
[11. 21.  1. ...  1. 21. 14.]
[15.  3.  6. ...  8. 13.  4.]
[[-200. -200. -200. ... -200. -200. -200.]
 [-200. -200. -200. ... -200. -200. -200.]
 [-200. -200. -200. ... -200. -200. -200.]
 ...
 [ -90. -200. -200. ... -200. -200. -200.]
 [-200. -200. -200. ... -200. -200. -200.]
 [-200. -200. -200. ... -200. -200. -200.]]
[-200. -200. -200. -200. -200. -200. -200.  -75. -200. -200. -200. -200.
 -200. -200. -200.]
[-200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200.
 -200. -200. -200.]
[-200. -200. -200. -200.  -89. -200. -200. -200. -200. -200.  -88. -200.
 -200. -200. -200.]
[-200. -200. -200. -200. -200. -200.  -71. -200. -200. -200. -200. -200.
 -200. -200. -200.]
[-200. -200. -200. -200. -200. -200. -200. -200.  -69. -200. -200. -200.
 -200. -200. -200.]
[-200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200.  -77.
 -200. -200. -200.]
[-200. -200. -200. -200. -200. -200.  -73. -200. -200. -200. -200. -200.
 -200. -200. -200.]
[-200. -200. -2